// react-js/react-tetris/src/components/Grid.js
import React from 'react';
import GridPiece from './GridPiece';

export default
class Grid extends React.Component {
    render() {
        let pieceSize = this.props.pieceSize;
        let key = 0;
        let staticPieces = [];
        for(let y=0; y<this.props.deckSize.gridY; y++){
            for(let x=0; x<this.props.deckSize.gridX; x++){
                if(this.props.deck[y][x] > 0){
                    staticPieces.push( <GridPiece key={key} color={this.props.deck[y][x]} size={pieceSize} posX={x} posY={y}/> );
                    key++;
                }
            }
        }
        return <div>{staticPieces}</div>;
    }
}

// vue-tetris/src/components/Grid.vue
<template>
    <div>
        <GridPiece v-for="(piece, index) in staticPieces"
                   :key="index"
                   :posX="piece.posX"
                   :posY="piece.posY"
                   :size="pieceSize"
                   :color="piece.color"
        />
    </div>
</template>

<script>

import GridPiece from './GridPiece'

    export default {
        name: "Grid",
        props: ['deck', 'deckSize', 'pieceSize'],
        components: {
            GridPiece
        },
        computed:{
            staticPieces:function(){
                let staticPieces = [];
                for(let y=0; y<this.deckSize.gridY; y++){
                    for(let x=0; x<this.deckSize.gridX; x++){
                        if(this.deck[y][x] > 0){
                            staticPieces.push(
                                {
                                    color:this.deck[y][x],
                                    posX:x,
                                    posY:y
                                }
                            );
                        }
                    }
                }
                return staticPieces;
            }
        }
    }
</script>
