// vue-js/vue-tetris/src/components/GridPiece.vue
<template>
    <div :class="pieceClass" :style="pieceStyle" />
</template>

<script>
    export default {
        name: "GridPiece",
        props: ['posX', 'posY', 'size', 'color'],
        computed:{
            pieceClass:function(){
                return 'piece color'+(this.color - 1);
            },
            pieceStyle:function(){
                return {
                    width:this.size + 'px',
                    height:this.size + 'px',
                    top:(this.posY * this.size)+ 'px',
                    left:(this.posX * this.size) + 'px',
                }
            }
        }
    }
</script>

<style scoped>
    .piece{
        position: absolute;
        border: solid 3px black;
        box-sizing: border-box;
        border-left-color: rgba(255,255,255,0.5);
        border-top-color: rgba(255,255,255,0.5);
        border-right-color: rgba(0,0,0,0.4);
        border-bottom-color: rgba(0,0,0,0.4);
        border-radius: 5px;
    }
    .color0{
        background-color: cyan;
    }
    .color1{
        background-color: blue;
    }
    .color2{
        background-color: orange;
    }
    .color3{
        background-color: yellow;
    }
    .color4{
        background-color: green;
    }
    .color5{
        background-color: magenta;
    }
    .color6{
        background-color: red;
    }
</style>

// react_js/react-tetris/src/components/GridPiece.js
import React from 'react';

export default
class GridPiece extends React.Component {
    render() {
        let pieceClass = 'piece color'+(this.props.color-1);
        let pieceStyle = {
            width:this.props.size + 'px',
            height:this.props.size + 'px',
            top:(this.props.posY * this.props.size)+ 'px',
            left:(this.props.posX * this.props.size) + 'px',
        };
        return <div className={pieceClass} style={pieceStyle} />;
    }
}
